version: '3.4'

services:
  api-idp-3:
    image: ndidplatform/api:latest
    environment:
      - ROLE=idp
      - NODE_ID=idp3
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-idp
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=api-idp-3
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${API_PORT:-8080}
    ports:
      - "8102:${API_PORT:-8080}"
  examples-idp-3:
    image: ndidplatform/ndid-examples-idp-dotnet
    environment:
      - KEYPATH=/keys
      - PERSISTANCEPATH=/persistances
      - API_SERVER_ADDRESS=http://api-idp-3:8080
      - CALLBACK_URL=http://examples-idp-3:80
    volumes:
      - ./persistances:/persistances
      - ./keys:/keys
    ports:
      - "8002:80"

networks:
  default:
    external:
      name: docker_ndidplatform