version: '3.4'

services:
  examples-idp-3:
    image: ndidplatform/ndid-examples-idp-dotnet
    environment:
      - KEYPATH=/keys
      - PERSISTANCEPATH=/persistances
      - API_SERVER_ADDRESS=http://api-idp-3:8080
    volumes:
      - ./persistance:/persistances
      - ./keys:/keys
    ports:
      - "8002:80"

networks:
  default:
    external:
      name: docker_ndidplatform